# Configure to your robot 

name: "Softbank_Nao"
devices:
  cameras: NULL
  gyroscopes: NULL
  accelerometers: NULL
  sensors: NULL

motor_names: {
  # HEAD
  "HeadYaw": "HeadYaw",
  "HeadPitch": "HeadPitch",
  "HeadRoll": NULL,
  
  # LEFT ARM
  "LFinger1": NULL,
  "LFinger2": NULL,
  "LFinger3": NULL,

  "LWristPitch": NULL,
  "LWristYaw": "LWristYaw",
  "LWristRoll": NULL,

  "LElbowPitch": "LElbowPitch",
  "LElbowRoll": "LElbowRoll",

  "LShoulderPitch": "LShoulderPitch",
  "LShoulderRoll": "LSHoulderRoll",

  # RIGHT ARM
  "RFinger1": NULL,
  "RFinger2": NULL,
  "RFinger3": NULL,

  "RWristPitch": NULL,
  "RWristYaw": "RWristYaw",
  "RWristRoll": NULL,

  "RElbowPitch": "RElbowPitch",
  "RElbowRoll": "RElbowRoll",

  "RShoulderPitch": "RShoulderPitch",
  "RShoulderRoll": "RShoulderRoll",
  
  # BODY
  "SpinePitch": NULL,
  "SpineYaw": NULL,
  "SpineRoll": NULL,

  "LowerSpinePitch": NULL,
  "LowerSpineYaw": NULL,
  "LowerSpineRoll": NULL,
  
  # LEFT LEG
  "LHipPitch": "LHipPitch",
  "LHipYaw": "LHipYaw",
  "LHipRoll": NULL,

  "LKneePitch": "LKneePitch",

  "LAnklePitch": "LAnklePitch",
  "LAnkleYaw": NULL,
  "LAnkleRoll": NULL,

  "LToes": NULL,

  # RIGHT LEG
  "RHipPitch": "RHipPitch",
  "RHipYaw": "RHipYaw",
  "RHipRoll": NULL,

  "RKneePitch": "RKneePitch",

  "RAnklePitch": "RAnklePitch",
  "RAnkleYaw": NULL,
  "RHRoll": NULL,

  "RToes": NULL
}
