import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { RobotMotionLanguageGeneratedModule, RobotMotionLanguageGeneratedSharedModule } from './generated/module';
import { RobotMotionLanguageValidationRegistry, RobotMotionLanguageValidator } from './robot-motion-language-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type RobotMotionLanguageAddedServices = {
    validation: {
        RobotMotionLanguageValidator: RobotMotionLanguageValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type RobotMotionLanguageServices = LangiumServices & RobotMotionLanguageAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const RobotMotionLanguageModule: Module<RobotMotionLanguageServices, PartialLangiumServices & RobotMotionLanguageAddedServices> = {
    validation: {
        ValidationRegistry: (services) => new RobotMotionLanguageValidationRegistry(services),
        RobotMotionLanguageValidator: () => new RobotMotionLanguageValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createRobotMotionLanguageServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    RobotMotionLanguage: RobotMotionLanguageServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        RobotMotionLanguageGeneratedSharedModule
    );
    const RobotMotionLanguage = inject(
        createDefaultModule({ shared }),
        RobotMotionLanguageGeneratedModule,
        RobotMotionLanguageModule
    );
    shared.ServiceRegistry.register(RobotMotionLanguage);
    return { shared, RobotMotionLanguage };
}
